# 기본 개념 쉽게 이해하기

1) 편차 : 평균(기댓값)으로부터 거리

2) 분산 : 평균으로부터 전체가 퍼져있는 정도

3) 확률분포

     (1) 이산확률 분포 : 특정 항목위주(셀 수 있음)

   - 베르누이 분포 : 두가지중 하나
   - 이항분포 : X번 시도 했을 때 K번 성공할 확률(베르누이를 X번 실행)
   - 기하분포 : 성공이 나올때까지 n번 시행 / 일반화 하면 음이항분포
   - 초기하 분포 : 이항분포를 비복원추출
   - 포아송 분포 : 이항분포를 무한반복, 발생할 수 있는 사건의 발생횟수

   (2) 연속확률 분포(셀 수 없음)
   - 균일분포 : 평균 (a+b)/2 / 분산 : (b-a)제곱 / 12
   - 정규분포 : 평균이 뮤, 표준편차가 알파 제곱
   - 표준평균분포 : 평균 0, 표준편차 1, 분산도 1
   - t-분포 : 자유도가 n, 평균 0, 좌우대칭 / 모평균 검정 또는 두 집단의 평균이 동일한지 계산
   - 카이제곱 분포 : 모평균과 모분산을 모름 / 모집단의 구성 파악을 위한 동질성 검정
   - F분포 : 분산분석에서 활용
   - 연속확률분포 : 셀 수 없는 변수, 면적이 곧 확률


4) 첨도, 왜도, 공분산, 상관계수

  - 첨도 : 뽀족한 정도, 3을 빼서 사용
  - 왜도 : 왜도가 크면 평균이 큼, 왼쪽이 뾰족함
  - 공분산 : E[(X-평균)(Y-평균)] / 상관정도, 최댓값 최솟값없음 / 선형관계
  - 상관계수 : 공분산의 문제를 해결 / -1~+1 사이 값 / 선형관계


# 선형회귀란?
1. 기본 개념

- 원인이 되는 데이터(X)를 가지고 결과가 될 데이터(Y)를 예측하는 가장 최적의 직선(Linear)을 그리는 작업

- 수리적 기본 형태 : y=ax+b

- 데이터 분석 형태 : y=wx+b

2. 가장 좋은 직선은?

- 최소제곱법을 기준으로 도출

- 실제 데이터 점들과 내가 그린 직선 사이의 세로 거리 측정

- 오차들을 전부 제곱해서 더하기

- 제곱된 오차들의 합이 가장 작아지는 순간의 기울기(w)와 절편(b) 값 찾기(미분 활용)

3. 최소제곱법이외의 기준

- 결정계수(r2_score) : 신뢰도 로서 직선이 얼마나 전체 데이터를 설명하는지 (0~1)

- 회귀계수 : 기울기 로써 데이터들의 영향력(w값)(p. 287 에선 다중선형회귀의 기울기값)

- p-value(유의확률) : 작을 수록 결과에 영향을 주는 중요한 원인





# 다중 선형 회귀?

1. 변수가 여러개인 항을 의미

- 단순선형회귀는 별로 사용하지 않으므로 생략

2. 형태

- y=bx+e (p.287 기준)

3. 실제 Y 값과 예측한 Y 값 사이의 오차를 제곱한 합을 최소로 만드는 b 과 e 를 도출

- 역행렬 활용


# LinearRegression 실습

https://scikit-learn.org/stable/


In [1]:
# 실습1

from sklearn.datasets import load_diabetes  # 당뇨 환자 데이터 셋
diabet = load_diabetes()
print(diabet.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

:Number of Instances: 442

:Number of Attributes: First 10 columns are numeric predictive values

:Target: Column 11 is a quantitative measure of disease progression one year after baseline

:Attribute Information:
    - age     age in years
    - sex
    - bmi     body mass index
    - bp      average blood pressure
    - s1      tc, total serum cholesterol
    - s2      ldl, low-density lipoproteins
    - s3      hdl, high-density lipoproteins
    - s4      tch, total cholesterol / HDL
    - s5      ltg, possibly log of serum triglycerides level
    - s6      glu, blood sugar level

Note: Each of these 10 feature variables have bee

당뇨병 데이터셋
----------------

# 설명 : 442명의 당뇨병 환자에 대한 속성을 기준으로 기준 시점 1년 후 질병 진행 측정

#1 인스턴스 수: 442개

#2 속성의 수: 10개

#3 Target: 열 11은 기준 후 1년 후 질병 진행을 정량적으로 측정한 것입니다

속성 종류:
- 나이(년)
- 성별
- 체질량지수
- 혈압 평균
- s1 tc, 총 혈청 콜레스테롤
- s2 ldl, 저밀도 지단백
- s3 hdl, 고밀도 지단백
- s4 tch, 총 콜레스테롤 / HDL
- s5 ltg, 혈청 중성지방 수치 로그일 가능성
- s6 글루, 혈당 수치

노트 : 이 10개의 특징 변수 각각은 표준 편차에 'n_샘플'의 제곱근(즉, 각 열의 제곱 합이 총 1)을 곱하여 평균 중심화되고 스케일링되었습니다.

In [4]:
# 실습 1 : 442명 환자 중 첫번째 환자의 속성 값
print(diabet.data[0])                                                 # 숫자가 이상하게 보이는 이유 : 표준화한 값으로 인해 수치가 속성과 다르게 보이는 것

[ 0.03807591  0.05068012  0.06169621  0.02187239 -0.0442235  -0.03482076
 -0.04340085 -0.00259226  0.01990749 -0.01764613]


In [5]:
# 실습 1-1 : 데이터를 예측하는 모델 기능

from sklearn.linear_model import LinearRegression    # 선형회귀 모델 적용
diabet_lr = LinearRegression()                       # diabet_lr 이라는 이름의 모델 사용
diabet_lr.fit(diabet.data, diabet.target)            # fit : data와 target(정답 : 당뇨병 진행도) 을 통한 데이터 학습

LinearRegression()

In [6]:
# 실습 1-2 : 예측 모델을 통해서 각 데이터의 속성 별 w값과 b값 계산

diabet_lr.coef_, diabet_lr .intercept_                # coef : 각각의 기울기   intercept : 절편 b값

(array([ -10.0098663 , -239.81564367,  519.84592005,  324.3846455 ,
        -792.17563855,  476.73902101,  101.04326794,  177.06323767,
         751.27369956,   67.62669218]),
 np.float64(152.13348416289597))

In [8]:
# 실습 1-3 : 442명 중 첫번째 환자의 속성값과 Target 값 확인

diabet.data[0], diabet.target[0]                     # 첫번째 값의 속성들  # target 값 : 정답(예측하려는 값)

(array([ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613]),
 np.float64(151.0))

In [9]:
# 실습 1-4 : 넘파이를 활용하여 첫번째 환자의 속성별 w, b 값을 적용하여 예측해보기 // 단순계산을 통해서

import numpy as np
np.sum(diabet.data[0] * diabet_lr.coef_)+diabet_lr.intercept_  # 예측값이 맞는지 증명해보기 : 206값으로 나와서 오차 발생(정답은 151)

np.float64(206.11667724510562)

In [13]:
# 실습 1-5 : 만든 예측모델을 활용하여 442명의 예측값을 도출

diabet_lr.predict(diabet.data)                       # predict : 데이터를 통해 예측하기

array([206.11667725,  68.07103297, 176.88279035, 166.91445843,
       128.46225834, 106.35191443,  73.89134662, 118.85423042,
       158.80889721, 213.58462442,  97.07481511,  95.10108423,
       115.06915952, 164.67656842, 103.07814257, 177.17487964,
       211.7570922 , 182.84134823, 148.00326937, 124.01754066,
       120.33362197,  85.80068961, 113.1134589 , 252.45225837,
       165.48779206, 147.71997564,  97.12871541, 179.09358468,
       129.05345958, 184.7811403 , 158.71516713,  69.47575778,
       261.50385365, 112.82234716,  78.37318279,  87.66360785,
       207.92114668, 157.87641942, 240.84708073, 136.93257456,
       153.48044608,  74.15426666, 145.62742227,  77.82978811,
       221.07832768, 125.21957584, 142.6029986 , 109.49562511,
        73.14181818, 189.87117754, 157.9350104 , 169.55699526,
       134.1851441 , 157.72539008, 139.11104979,  72.73116856,
       207.82676612,  80.11171342, 104.08335958, 134.57871054,
       114.23552012, 180.67628279,  61.12935368,  98.72

In [12]:
# 실습 1- 6: MSE 계산
#     정답지(y)    예측모델을 통한 각 환자의 예측값  :
# diabet.target - diabet_lr.predict(diabet.data) : 오차(=잔차)

np.mean((diabet.target - diabet_lr.predict(diabet.data))**2)   # 전체 데이터들의 오차의 평균(p286 잔차)

np.float64(2859.69634758675)

In [14]:
# 실습 1-7 : 신뢰도를 활용하는 r2_score 사용

from sklearn.metrics import r2_score                         # 선형회귀에서는 사용가능함, 딥러닝에서는 계산불가
r2_score(diabet.target, diabet_lr.predict(diabet.data))      # 해당 모델의 신회도가 51% 임을 설명하는 중

0.5177484222203499