# 0. sklearn 관련 복습
### 통계분석 2일차(당뇨병)
### 통계분석 3일차(당뇨병, 유방암)

# 1. K-NN 알고리즘 분류모델

In [ ]:
# 사용한 라이브러리
# import numpy as np
# from sklearn.datasets import load_iris
# from sklearn.preprocessing import StandardScaler
# from sklearn.model_selection import train_test_split
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
# 실습 #1 아이리스 데이터를 활용한 실습

from sklearn.datasets import load_iris

iris = load_iris()
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [ ]:
iris.data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [ ]:
# 전처리(표준화)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris.data)                    # iris 데이터를 활용해서 기준 잡기
iris_data = scaler.transform(iris.data)  # 그 기준을 통해 ()데이터를 조정하기

# 기준을 잡을 데이터의 경우 scaler.fit_transform() 로 한번에 적용가능함


print(iris_data[:10])

[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]
 [-0.53717756  1.93979142 -1.16971425 -1.05217993]
 [-1.50652052  0.78880759 -1.34022653 -1.18381211]
 [-1.02184904  0.78880759 -1.2833891  -1.3154443 ]
 [-1.74885626 -0.36217625 -1.34022653 -1.3154443 ]
 [-1.14301691  0.09821729 -1.2833891  -1.44707648]]


In [ ]:
iris.target[:3]

array([0, 0, 0])

In [ ]:
iris_data[:3]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ]])

In [ ]:
# train, test 데이터 분류

from sklearn.model_selection import train_test_split

#   iris_data       iris.target
x_train, x_test, y_train, y_test = train_test_split(iris_data, iris.target,
                                                    test_size=0.3,              # train, test 데이터 규모 조정
                                                    stratify = iris.target,     # 층화추출 적용
                                                    random_state=629)           # 데이터 고정
print(x_train.shape, y_test.shape)

(105, 4) (45,)


In [ ]:
# 라벨당 데이터 확인

import numpy as np

print(np.unique(y_test, return_counts=True))  # 불균형 상태 점검

(array([0, 1, 2]), array([15, 15, 15]))


In [ ]:
# KNN 알고리즘

from sklearn.neighbors import KNeighborsClassifier

iris_knn = KNeighborsClassifier()                 # n_neighbors 값이 K 값(기본값은 5)
iris_knn.fit(x_train, y_train)                    # 학습시키기(데이터 <-> 정답)
pred = iris_knn.predict(x_test)                   # 예측해보기
print(pred)

[1 2 2 0 0 2 0 2 0 2 1 2 0 2 1 2 2 1 1 1 0 0 2 0 1 2 1 0 2 0 1 0 1 2 1 0 1
 2 1 0 1 1 0 0 1]


In [ ]:
# 예측 검증하기

from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_test, pred))                          # 정확도(정답 <-> 예측값)




'''
0번을 0으로 15개 예측
1번을 1번으로 14개, 2번으로 1개
2번을 1번으로 2개, 2번으로 13개 분류함
'''
print(confusion_matrix(y_test, pred))                        # 분포도(정답 <-> 예측값)



0.9333333333333333
[[15  0  0]
 [ 0 14  1]
 [ 0  2 13]]


In [ ]:
# K값 찾기

for k in range(1,16): # k값을 15까지 돌리기
    iris_knn = KNeighborsClassifier(n_neighbors=k)  # 원래의 k 값은 데이터 수의 제곱근으로 하면 됨(100여개 -> 10여개로)
    iris_knn.fit(x_train, y_train)
    pred = iris_knn.predict(x_test)
    print(k, accuracy_score(y_test, pred))          # 최적의 k값 찾기

1 0.9555555555555556
2 0.9555555555555556
3 0.9555555555555556
4 0.9333333333333333
5 0.9333333333333333
6 0.9555555555555556
7 0.9555555555555556
8 0.9555555555555556
9 0.8888888888888888
10 0.9555555555555556
11 0.9555555555555556
12 0.9777777777777777
13 0.9333333333333333
14 0.9777777777777777
15 0.9555555555555556


In [ ]:
# 실습 2 train, test 데이터 적용 다른 방식(train 데이터만 표준화 시킨 경우)


x_train, x_test, y_train, y_test = train_test_split(iris_data, iris.target,
                                                    test_size=0.3,              # train, test 데이터 규모 조정
                                                    stratify = iris.target,     # 층화추출 적용
                                                    random_state=629)           # 데이터 고정

# 데이터의 양이 많을 경우(예측할 데이터가 많을 경우) 학습시키는 방식(실무에서 적용됨)

scaler = StandardScaler()
scaler.fit(x_train)                       # train 데이터만 표준화 하여 학습
x_train_std = scaler.transform(x_train)   # train 데이터 조정
x_test_std = scaler.transform(x_test)     # test 데이터 조정

In [ ]:
# 실습 2-1 K 값 도출

for k in range(1,16):
    iris_knn = KNeighborsClassifier(n_neighbors=k)
    iris_knn.fit(x_train_std, y_train)
    pred = iris_knn.predict(x_test_std)
    print(k, accuracy_score(y_test, pred))

1 0.9555555555555556
2 0.9333333333333333
3 0.9555555555555556
4 0.9333333333333333
5 0.9333333333333333
6 0.9555555555555556
7 0.9555555555555556
8 0.9555555555555556
9 0.8888888888888888
10 0.9555555555555556
11 0.9555555555555556
12 0.9777777777777777
13 0.9333333333333333
14 0.9777777777777777
15 0.9555555555555556


In [ ]:
# 실습 3 train, test 데이터 적용 다른 방식(정규화 적용)

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris.data)
iris_data = scaler.transform(iris.data)

x_train, x_test, y_train, y_test = train_test_split(iris_data, iris.target,
                                                    test_size=0.3,
                                                    stratify = iris.target,
                                                    random_state=629)

for k in range(1,31):
    iris_knn = KNeighborsClassifier(n_neighbors=k)
    iris_knn.fit(x_train, y_train)
    pred = iris_knn.predict(x_test)
    print(k, accuracy_score(y_test, pred))

1 0.9555555555555556
2 0.9555555555555556
3 0.9555555555555556
4 0.9333333333333333
5 0.9555555555555556
6 0.9555555555555556
7 0.9555555555555556
8 0.9555555555555556
9 0.9555555555555556
10 0.9555555555555556
11 0.9555555555555556
12 0.9555555555555556
13 0.9555555555555556
14 0.9555555555555556
15 0.9555555555555556
16 0.9555555555555556
17 0.9555555555555556
18 0.9777777777777777
19 0.9555555555555556
20 0.9555555555555556
21 0.9555555555555556
22 0.9777777777777777
23 0.9555555555555556
24 0.9777777777777777
25 0.9555555555555556
26 0.9777777777777777
27 0.9555555555555556
28 0.9555555555555556
29 0.9333333333333333
30 0.9111111111111111


In [ ]:
# 실습 4 breast cancer 적용(정규화 vs 표준화)

from sklearn.datasets import load_breast_cancer

bc = load_breast_cancer()
print(bc.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - 

In [ ]:
# 실습 4-1 정규화

scaler = MinMaxScaler()
scaler.fit(bc.data)
bc_data = scaler.transform(bc.data)

x_train, x_test, y_train, y_test = train_test_split(bc_data, bc.target,
                                                    test_size=0.3,
                                                    stratify = bc.target,
                                                    random_state=629)

for k in range(1,31):
    bc_knn = KNeighborsClassifier(n_neighbors=k)
    bc_knn.fit(x_train, y_train)
    pred = bc_knn.predict(x_test)
    print(k, accuracy_score(y_test, pred))     # k= 15 에서 98.246%

1 0.9473684210526315
2 0.9415204678362573
3 0.9590643274853801
4 0.9532163742690059
5 0.9590643274853801
6 0.9590643274853801
7 0.9707602339181286
8 0.9649122807017544
9 0.9707602339181286
10 0.9707602339181286
11 0.9707602339181286
12 0.9649122807017544
13 0.9766081871345029
14 0.9707602339181286
15 0.9824561403508771
16 0.9707602339181286
17 0.9766081871345029
18 0.9766081871345029
19 0.9766081871345029
20 0.9766081871345029
21 0.9766081871345029
22 0.9766081871345029
23 0.9766081871345029
24 0.9766081871345029
25 0.9707602339181286
26 0.9707602339181286
27 0.9707602339181286
28 0.9649122807017544
29 0.9649122807017544
30 0.9649122807017544


In [ ]:
# 실습 4-2 표준화

scaler = StandardScaler()
scaler.fit(bc.data)
bc_data = scaler.transform(bc.data)

x_train, x_test, y_train, y_test = train_test_split(bc_data, bc.target,
                                                    test_size=0.3,
                                                    stratify = bc.target,
                                                    random_state=629)


for k in range(1,31):
    bc_knn = KNeighborsClassifier(n_neighbors=k)
    bc_knn.fit(x_train, y_train)
    pred = bc_knn.predict(x_test)
    print(k, accuracy_score(y_test, pred))            # k=21 에서 98.246%

1 0.9532163742690059
2 0.9415204678362573
3 0.9590643274853801
4 0.9590643274853801
5 0.9590643274853801
6 0.9590643274853801
7 0.9649122807017544
8 0.9590643274853801
9 0.9590643274853801
10 0.9590643274853801
11 0.9649122807017544
12 0.9649122807017544
13 0.9707602339181286
14 0.9707602339181286
15 0.9649122807017544
16 0.9707602339181286
17 0.9766081871345029
18 0.9766081871345029
19 0.9766081871345029
20 0.9766081871345029
21 0.9824561403508771
22 0.9824561403508771
23 0.9766081871345029
24 0.9707602339181286
25 0.9766081871345029
26 0.9707602339181286
27 0.9766081871345029
28 0.9707602339181286
29 0.9766081871345029
30 0.9707602339181286


In [ ]:
# 실습 5 교차검증 : StratifiedKFold 이해

from sklearn.model_selection import StratifiedKFold

s_kfold = StratifiedKFold(5) # 5조각으로 분류할 것이다 -> 인덱스로 리턴함

                                       # 일반 데이터, target 데이터
for train_idx, test_idx in s_kfold.split(range(100), [0]*50+[1]*50):

# 100개를 5개로 나눠서 20개는 테스트 데이터, 80개는 트레이닝 데이터로 만들어줌
# 일반 데이터 수와 target 데이터 수가 다르면 오류 발생

  print("트레이닝 데이터 \n" , train_idx)
  print("테스트 데이터 \n", test_idx)

트레이닝 데이터 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99]
테스트 데이터 
 [ 0  1  2  3  4  5  6  7  8  9 50 51 52 53 54 55 56 57 58 59]
트레이닝 데이터 
 [ 0  1  2  3  4  5  6  7  8  9 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99]
테스트 데이터 
 [10 11 12 13 14 15 16 17 18 19 60 61 62 63 64 65 66 67 68 69]
트레이닝 데이터 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99]
테스트 데이터 
 [20 21 22 23 24 25 26 27 28 29 70 71 72 73 74 75 76 77 78 79]
트레이닝 데이터 
 [ 0  

In [ ]:
# 실습 5-1 적용
s_kfold = StratifiedKFold(5)


for train_idx, test_idx in s_kfold.split(bc.data, bc.target):
  scaler = StandardScaler() # 표준화
  scaler.fit(bc.data[train_idx])                 # StratifiedKFold로 분류한 부분에 대해서 train 데이터를 기준으로 적용(스케일 조정)
  x_train = scaler.transform(bc.data[train_idx]) # 해당 기준에 맞춰 train 데이터 적용
  x_test = scaler.transform(bc.data[test_idx])   # 해당 기준에 맞춰 test 데이터 적용

  for k in range(1,50,2):
    bc_knn = KNeighborsClassifier(n_neighbors=k)
    bc_knn.fit(x_train, bc.target[train_idx])
    pred = bc_knn.predict(x_test)
    print(k, accuracy_score( bc.target[test_idx], pred))
  print("========")

1 0.956140350877193
3 0.9736842105263158
5 0.9649122807017544
7 0.9736842105263158
9 0.9649122807017544
11 0.9649122807017544
13 0.9649122807017544
15 0.9649122807017544
17 0.956140350877193
19 0.9473684210526315
21 0.9385964912280702
23 0.9385964912280702
25 0.9385964912280702
27 0.9298245614035088
29 0.9385964912280702
31 0.9385964912280702
33 0.9298245614035088
35 0.9298245614035088
37 0.9385964912280702
39 0.9385964912280702
41 0.9385964912280702
43 0.9210526315789473
45 0.9210526315789473
47 0.9298245614035088
49 0.9298245614035088
1 0.9736842105263158
3 0.9649122807017544
5 0.956140350877193
7 0.956140350877193
9 0.9473684210526315
11 0.9385964912280702
13 0.9385964912280702
15 0.9385964912280702
17 0.9298245614035088
19 0.9385964912280702
21 0.9385964912280702
23 0.9298245614035088
25 0.9298245614035088
27 0.9298245614035088
29 0.9298245614035088
31 0.9298245614035088
33 0.9298245614035088
35 0.9210526315789473
37 0.9210526315789473
39 0.9210526315789473
41 0.9210526315789473
43

In [ ]:
# 실습 5-2 가장 높은 평균 정확도의 K 값 구하기(나의 풀이)
# 한번에 해주는 코드(자동화) 존재하기에 원리정도만 알기

s_kfold = StratifiedKFold(5)
k_scores = {k: [] for k in range(1, 50, 2)} # K 값을 얼추 알고 있기 때문에 그냥 K 값에 따른 공간을 만들어줌

for train_idx, test_idx in s_kfold.split(bc.data, bc.target):
  scaler = StandardScaler()
  scaler.fit(bc.data[train_idx])
  x_train = scaler.transform(bc.data[train_idx])
  x_test = scaler.transform(bc.data[test_idx])

  for k in range(1,50,2):
    bc_knn = KNeighborsClassifier(n_neighbors=k)
    bc_knn.fit(x_train, bc.target[train_idx])
    pred = bc_knn.predict(x_test)

    score = accuracy_score(bc.target[test_idx], pred) # 각 예측 한 값의 정확도
    k_scores[k].append(score)                         # K_scores에 넣기(딕셔너리 키-벨류 활용)

best_k = 0
best_score = 0

print(" 5-Fold K값 평균 정확도 ")
for k, scores in k_scores.items():
    mean_score = np.mean(scores)
    print(f"K = {k} : {mean_score:.4f}")

    if mean_score > best_score:
        best_score = mean_score
        best_k = k

print("================================")
print(f"최종 : K = {best_k} (평균 정확도: {best_score:.4f})")

 5-Fold K값 평균 정확도 
K = 1 : 0.9543
K = 3 : 0.9595
K = 5 : 0.9649
K = 7 : 0.9701
K = 9 : 0.9666
K = 11 : 0.9649
K = 13 : 0.9666
K = 15 : 0.9614
K = 17 : 0.9596
K = 19 : 0.9561
K = 21 : 0.9561
K = 23 : 0.9508
K = 25 : 0.9526
K = 27 : 0.9526
K = 29 : 0.9543
K = 31 : 0.9526
K = 33 : 0.9508
K = 35 : 0.9491
K = 37 : 0.9508
K = 39 : 0.9508
K = 41 : 0.9508
K = 43 : 0.9491
K = 45 : 0.9491
K = 47 : 0.9491
K = 49 : 0.9508
최종 : K = 7 (평균 정확도: 0.9701)


# StandardScaler().fit(x) : "분포가 어느 정도니?"

  "이 데이터(X)들의 평균이 얼마고, 최댓값/최솟값이 얼마인가?".

  " 스케일 조정 시 "

# KNeighborsClassifier().fit(x, y) : "이런 애들(x)은 정답(y)이 뭐니?"

  "세포 크기가 이 정도(X)면, 주로 악성 종양(y)"

# 데이터를 가공하고 변환하는 도구들 (스케일러, 결측치 채우기 등):

정답이 필요 없으므로 .fit(X) 만 사용

# 미래를 예측하고 맞추는 모델들 (KNN, 의사결정나무, 랜덤포레스트 등):

문제와 정답을 함께 보고 학습해야 하므로 .fit(X, y) 형태로 사용